### ISSUE TITLE
increment sdkMinimumVersion

### ISSUE THREAD

**Issue by kv08031993** [AnySoftKeyboard/AnySoftKeyboard#1155]
i change sdkMinimumVersion = 7 to 15

it shows the error

**Comment by menny** [comment]
Please paste the error you get. Also, there was a similar issue that is fixed on _master_. Please verify that

**Comment by kv08031993** [comment]
10-27 12:12:01.405 30254-30254/? E/eLock: startWatching
10-27 12:12:25.475 30238-30238/com.ds.keyboard E/dalvikvm: VM aborting
10-27 12:12:25.476 30238-30238/com.ds.keyboard A/libc: Fatal signal 6 (SIGABRT) at 0x0000761e (code=-6), thread 30238 (com.ds.keyboard)
10-27 12:12:25.476 30238-30238/com.ds.keyboard A/libc: Send stop signal to pid:30238 in void debuggerd_signal_handler(int, siginfo_t*, void*)
10-27 12:12:27.745 738-946/? E/NativeCrashListener: Exception dealing with report
                                                    libcore.io.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:128)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
10-27 12:12:35.999 738-779/? E/InputDispatcher: channel '42523f60 com.ds.keyboard/com.ds.keyboard.LauncherSettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
 this error show in old project...

**Comment by kv08031993** [comment]
10-27 12:12:01.405 30254-30254/? E/eLock: startWatching
10-27 12:12:25.475 30238-30238/ E/dalvikvm: VM aborting
10-27 12:12:25.476 30238-30238/libc: Fatal signal 6 (SIGABRT) at 0x0000761e (code=-6), thread 30238 
10-27 12:12:25.476 30238-30238/libc: Send stop signal to pid:30238 in void debuggerd_signal_handler(int, siginfo_t*, void*)
10-27 12:12:27.745 738-946/? E/NativeCrashListener: Exception dealing with report
                                                    libcore.io.ErrnoException: read failed: EAGAIN (Try again)
                                                        at libcore.io.Posix.readBytes(Native Method)
                                                        at libcore.io.Posix.read(Posix.java:128)
                                                        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:149)
                                                        at com.android.server.am.NativeCrashListener.consumeNativeCrashData(NativeCrashListener.java:240)
                                                        at com.android.server.am.NativeCrashListener.run(NativeCrashListener.java:138)
10-27 12:12:35.999 738-779/? E/InputDispatcher: channel '42523f60 com.ds.keyboard/com.ds.keyboard.LauncherSettingsActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by kv08031993** [comment]
this error shows in old project

**Comment by kv08031993** [comment]
and gesture detector not work smoothly...

**Comment by menny** [comment]
Two things: First, try to use the latest code. As I mentioned, a similar issue was solved about a month ago.
Second, if you experience issues with the gesture detector you can either try to fix it (this is an open-source project), or open another issue with a clear description of the problem.
