### ISSUE TITLE
An index out of bound exception while typing text into Firefox

### ISSUE THREAD

**Issue by marmistrz** [AnySoftKeyboard/AnySoftKeyboard#1724]
I was typing in Firefox (downloaded using FFUpdater) and suddenly ASK crashed

```
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 22:55:33 12.05.2019
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.10.364 release 5539. Installed on 1554080097695, first release installed was 4630.
******************************
****** Exception type: java.lang.StringIndexOutOfBoundsException
****** Exception message: length=106; regionStart=106; regionLength=-106
****** Trace trace:
at java.lang.String.substring(String.java:1931)
at java.lang.String.subSequence(String.java:1969)
at com.anysoftkeyboard.AnySoftKeyboard.C(AnySoftKeyboard.java:937)
at com.anysoftkeyboard.AnySoftKeyboard.b(AnySoftKeyboard.java:1004)
at com.anysoftkeyboard.keyboards.views.v.a(PointerTracker.java:255)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.b(AnyKeyboardViewBase.java:1804)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.a(AnyKeyboardViewBase.java:1783)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.onTouchEvent(AnyKeyboardViewBase.java:1762)
at com.anysoftkeyboard.keyboards.views.h.onTouchEvent(AnyKeyboardViewWithMiniKeyboard.java:100)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onTouchEvent(AnyKeyboardView.java:279)
at android.view.View.dispatchTouchEvent(View.java:10024)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2632)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2264)
at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:416)
at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1808)
at android.app.Dialog.dispatchTouchEvent(Dialog.java:806)
at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:93)
at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:378)
at android.view.View.dispatchPointerEvent(View.java:10244)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4444)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4312)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4005)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4062)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3912)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3878)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3886)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3859)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6253)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6227)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6188)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6356)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:323)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:6186)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

******************************
****** Device information:
BRAND:OnePlus
DEVICE:OnePlus3
Build ID:lineage_oneplus3-userdebug 7.1.2 NJH47F 85f4b345c4
changelist number:NJH47F
MODEL:ONEPLUS A3003
PRODUCT:lineage_oneplus3
TAGS:release-keys
VERSION.INCREMENTAL:85f4b345c4
VERSION.RELEASE:7.1.2
VERSION.SDK_INT:25
Locale:en_US
configuration:{1.0 260mcc1mnc [en_US,zh_TW_#Hant,zh_CN_#Hans,ru_RU] ldltr sw360dp w360dp h616dp 480dpi nrml long port finger -keyb/v/h -nav/h s.51}
That's all I know.******************************
****** Log-Cat:
Log contains 0 lines:
```

**Comment by ArenaL5** [comment]
Whatever line caused this error in the code doesn't exist anymore. This bug is no longer relevant.

**Comment by AnXh3L0** [comment]
Closing bug as fixed.
