### ISSUE TITLE
Keyboard freezes and stuck on the screen after hit emojis

### ISSUE THREAD

**Issue by Monti94** [AnySoftKeyboard/AnySoftKeyboard#1860]
### Steps to reproduce
1. Open keyboard, hit emoji and go back several times. Long or short press, by default it's long, I made it short press, makes no difference

### Expected behaviour
Open the emojis

### Actual behaviour
Sometimes when I want to open the emoji popup, it freezes like you can see on the picture, sometimes after I hit home, it disappears after several seconds, but 90% of the case, it stays there until I go with my half-screen to settings, apps, find the main ASK app, and force close it. Theme change, reinstall, factory reset does not matter. It happens regularly with the stable, and with BETA also. I'll try it with my other device, what is a Huawei P10 lite.

**Android OS version:**
Android 9, Oxygen OS 9.0.8

**Device manufacturer and model:**
Oneplus 5, 8@128GB

**List of installed add-ons (like languages, or themes):**
Hungarian language, nothing else, layout is 4 row qwertz with accentuated letters in the first row, numbers in top row, and the bottom line is Classical with no microphone.

Here you have a screenshot from the issue. 
![Screenshot_20191008-162359](https://user-images.githubusercontent.com/56348006/66478084-dd95f900-ea99-11e9-9740-3b3d0bd13d36.jpg)

**Comment by Monti94** [comment]
Unfortunately, the problem is still actual and the same, after factory reset, and now not on stable Osygen OS version, but on Open Beta 35...

![Screenshot_20191017-163113](https://user-images.githubusercontent.com/56348006/67019101-6cd78800-f0fc-11e9-87b1-54dcbd7bee55.jpg)

![Screenshot_20191017-164158](https://user-images.githubusercontent.com/56348006/67019523-1585e780-f0fd-11e9-99a2-ae6411caa195.jpg)

**Comment by bijindas** [comment]
me too facing the same issue... 🙄

**Comment by Soulthym** [comment]
Same issue here, been happening for over a year now, between once every 2-3 days to a dozen times a day, and never stopped. It's getting so annoying that I am thinking of switching to another keyboard, which is a shame because none are as good and OpenSource. I have no idea what causes this to happen, but to what I remember it only happens on Messenger, but I could be wrong (given that that's the only thing I do on my phone using the keyboard, I don't know what this is worth...)

**Comment by DidierLmn** [comment]
Same issue on Nokia 8.1 Android 9 and later android 1
As well as Mi 8 with LineageOS 16 and later LineageOS 17.1 (based on Android 9 and 10 respectively)

The entire phone even becomes unresponsive for a few seconds

**Comment by menny** [comment]
I'll need more information, as I'm unable to reproduce this.
Are you on the beta channel?
Which Quick-Text addon (emoji groups) do you have enabled?

**Comment by Monti94** [comment]
Not just emoji, but any of the long-press keys can trigger it, but the emoji is the most common. 
I have these groups enabled, does not make any difference if I enable more, or disable. It happens on Android 10 Beta 1 also (oxygenOS), and the app version also doesn't make difference, and the beta/non-beta version also not. It happens every recent version, you can trigger it. Try to open the keyboard, open emojis few times, close the keyboard. and repeat this, it will freeze after a few attempts. :)
![Screenshot_20200522-111827](https://user-images.githubusercontent.com/56348006/82652497-ff558200-9c1d-11ea-90fd-0a131ab8182e.jpg)

**Comment by DidierLmn** [comment]
In my case I am not running a beta version. And can confirm that the bug is not always present, but it happens on average twice a week.

AnySoftKeyboard v1.10-r3 installed through F-Droid

Languages: English QWERTY Latin keyboard + Dutch (by Stichting OpenTaal)

UI: Power-Saving Mode

Quick Text Groups enabled:
- emoticons
- people
- accessories
- nature
- food
- transport
- signs
- scape
- activity
- office
- occasions
- flags 
- kaomoji

Would a backup of my settings be useful?

**Comment by menny** [comment]
Yes, if you can send me your settings backup file that would be helpful.
Also, would you mind trying out the beta build? I made a fix a few days ago that could help with this.

**Comment by DidierLmn** [comment]
Here are my settings backup
[AnySoftKeyboardPrefs.xml.zip](https://github.com/AnySoftKeyboard/AnySoftKeyboard/files/4695171/AnySoftKeyboardPrefs.xml.zip)

I would try the beta, but according to the Play Store the beta program is full and I cannot join. Do you distribute the beta built elsewhere?

**Comment by Peter-JanGootzen** [comment]
I have been experiencing this exact issue on the f-droid build for a few months now and today tried out the Google Play beta build without any luck. I would be happy to provide any information for reproducing the issue, I'm running Android 10 on with MIUI 12.0.2.
AnySoftKeyboard is amazing, so having this single issue drag it down is really a waste.

**Comment by menny** [comment]
would you mind running a development version? And pass back any logs (we can pass logs privately if you prefer)

**Comment by Monti94** [comment]
Hi,

Sure, I would be happy, the current state of my devices are: my Open Beta
OxygenOS10 ROM died on me (telephony error, no SIM recognition, second
time, older and newer build did it also), so I've moved to AICP v15.0
today. Since 12 hours, I did not have any crashes, but on my other phone
(Oukitel K10000 pro) on Android 7.0 does the same thing, the difference is,
that device shows the notification 'it wasn't expected' or something
similar, but still freezes as much as I still can't send the bugreport,
because it does not open the app at all, until I force close it, but then
the error notification disappears also. I would use the mentioned test
build on my Oukitel, which has the same problem (maybe more often, in this
case it's good for us), I think the problem is the same on Android 7 and 10
also.

Best regards: Monti

Menny Even Danan <notifications@github.com> ezt írta (időpont: 2020. aug.
17., H 0:17):

**Comment by Peter-JanGootzen** [comment]
> would you mind running a development version? And pass back any logs (we can pass logs privately if you prefer)

Is the beta version from the Google Play store okay for that (v1.10.1559 version-code 6729)?

How do I go about extracting these logs? And do they contain my key presses (like a keylogger)?

**Comment by menny** [comment]
the logs _will_ include key-presses.

**Comment by Monti94** [comment]
It started the thing on AICP also! so I can test it with the test build. :)

Bence Kovács <kbence13@gmail.com> ezt írta (időpont: 2020. aug. 17., H
2:48):

**Comment by domportera** [comment]
I'm having this issue as well. here is a video and a log of what I'm experiencing. I'm on the Google Play Beta (Canary)

the log says this is caused by null emoji values, possiboy caused by a recent update. a simple null check and set default may be able to patch this.

```
. It seems that we have crashed.... Here are some details:
****** UTC Time: 01:49:01 25.08.2022
****** Application name: AnySoftKeyboard Canary (com.menny.android.anysoftkeyboard) v1.11.582 release 7542. Installed on 1660323781145, first release installed was 6964.
******************************
java.lang.IllegalArgumentException
****** Exception message: can not have both skin-tone and gender set to null!
----- FULL REPORT -----
****** Trace trace:
at i2.g.b(SourceFile:13)
at i2.o.i(SourceFile:2)
at i2.e.v(Unknown Source:2)
at i2.e.i(Unknown Source:24)
at i2.g.<init>(Unknown Source:20)
at s2.b.f(SourceFile:4)
at q1.f.a(Unknown Source:9)
at q1.f.r(Unknown Source:99)
at q1.f.q(Unknown Source:2)
at q1.f.onMeasure(Unknown Source:189)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:25815)
at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1185)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChild(ViewGroup.java:7042)
at com.anysoftkeyboard.keyboards.views.KeyboardViewContainerView.onMeasure(Unknown Source:47)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:25815)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7071)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:808)
at android.view.View.measure(View.java:25815)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3709)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2471)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2754)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2185)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8988)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
at android.view.Choreographer.doCallbacks(Choreographer.java:926)
at android.view.Choreographer.doFrame(Choreographer.java:859)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8001)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)

******************************
****** Device information:
BRAND:lge
DEVICE:timelm
Build ID:SKQ1.211103.001
changelist number:SKQ1.211103.001
MODEL:LM-V600
PRODUCT:timelm
TAGS:release-keys
VERSION.INCREMENTAL:221861514ef56
VERSION.RELEASE:12
VERSION.SDK_INT:31
Locale:en_US
configuration:{0.78 310mcc260mnc [en_US] ldltr sw411dp w411dp h908dp 420dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2460) mAppBounds=Rect(0, 76 - 1080, 2460) mMaxBounds=Rect(0, 0 - 1080, 2460) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.1 s.47008 fontWeightAdjustment=0 fontTypeIndex=0 forceEmbolden0}
That's all I know.
******************************
****** Log-Cat: 
Log contains 0 lines:
```

When attempting to fix this by setting the settings myself, it also crashes with the same error:

 ```
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 01:55:34 25.08.2022
****** Application name: AnySoftKeyboard Canary (com.menny.android.anysoftkeyboard) v1.11.582 release 7542. Installed on 1660323781145, first release installed was 6964.
******************************
java.lang.IllegalArgumentException
****** Exception message: can not have both skin-tone and gender set to null!
----- FULL REPORT -----
****** Trace trace:
at i2.g.b(SourceFile:13)
at i2.o.i(SourceFile:2)
at i2.e.v(Unknown Source:2)
at i2.e.i(Unknown Source:24)
at i2.g.<init>(Unknown Source:20)
at com.anysoftkeyboard.quicktextkeys.ui.QuickTextKeysBrowseFragment.n0(SourceFile:5)
at z2.d.f(SourceFile:8)
at androidx.recyclerview.widget.g1.k(SourceFile:83)
at androidx.recyclerview.widget.h0.c(SourceFile:3)
at androidx.recyclerview.widget.GridLayoutManager.e1(SourceFile:5)
at androidx.recyclerview.widget.LinearLayoutManager.R0(SourceFile:2)
at androidx.recyclerview.widget.LinearLayoutManager.i0(SourceFile:19)
at androidx.recyclerview.widget.GridLayoutManager.i0(SourceFile:7)
at androidx.recyclerview.widget.RecyclerView.s(SourceFile:2)
at androidx.recyclerview.widget.RecyclerView.q(SourceFile:6)
at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(Unknown Source:49)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:850)
at android.view.View.layout(View.java:23185)
at android.view.ViewGroup.layout(ViewGroup.java:6503)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3782)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3229)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2185)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8988)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1120)
at android.view.Choreographer.doCallbacks(Choreographer.java:926)
at android.view.Choreographer.doFrame(Choreographer.java:859)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1105)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:8001)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1039)

******************************
****** Device information:
BRAND:lge
DEVICE:timelm
Build ID:SKQ1.211103.001
changelist number:SKQ1.211103.001
MODEL:LM-V600
PRODUCT:timelm
TAGS:release-keys
VERSION.INCREMENTAL:221861514ef56
VERSION.RELEASE:12
VERSION.SDK_INT:31
Locale:en_US
configuration:{0.78 310mcc260mnc [en_US] ldltr sw411dp w411dp h908dp 420dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2460) mAppBounds=Rect(0, 76 - 1080, 2460) mMaxBounds=Rect(0, 0 - 1080, 2460) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.1 s.47008 fontWeightAdjustment=0 fontTypeIndex=0 forceEmbolden0}
That's all I know.
******************************
****** Log-Cat: 
Log contains 0 lines:
```

**Comment by mirenbz** [comment]
Hi, any progress on this? I'm experiencing the same issue on Android 13, running the beta from GPlay because I couldn't import my settings otherwise. I sent a crash report through email earlier, but just wondering if anyone had any success in fixing this... Thanks!

**Comment by menny** [comment]
Can you attach the crash log here?

**Comment by mirenbz** [comment]
Sure, here the contents of the log file:

```
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 19:41:56 04.05.2023
****** Application name: AnySoftKeyboard Canary (com.menny.android.anysoftkeyboard) v1.12.138 release 7766. Installed on 1683131938449, first release installed was 6956.
******************************
java.lang.IllegalArgumentException
****** Exception message: can not have both skin-tone and gender set to null!
----- FULL REPORT -----
****** Trace trace:
at t1.g.b(SourceFile:11)
at t1.k.i(SourceFile:200)
at t1.e.w(SourceFile:3)
at t1.e.i(SourceFile:33)
at t1.g.<init>(Unknown Source:20)
at androidx.viewpager.widget.a.a(SourceFile:167)
at androidx.viewpager.widget.a.r(SourceFile:327)
at androidx.viewpager.widget.a.q(Unknown Source:2)
at androidx.viewpager.widget.a.onMeasure(Unknown Source:189)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27720)
at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1185)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChild(ViewGroup.java:7323)
at com.anysoftkeyboard.keyboards.views.KeyboardViewContainerView.onMeasure(Unknown Source:47)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
at android.view.View.measure(View.java:27720)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1380)
at android.view.View.measure(View.java:27720)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4841)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3426)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3732)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
at android.view.Choreographer.doCallbacks(Choreographer.java:923)
at android.view.Choreographer.doFrame(Choreographer.java:852)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

******************************
****** Device information:
BRAND:samsung
DEVICE:x1q
Build ID:TP1A.220624.014.G981NKSU3IWCG
changelist number:TP1A.220624.014
MODEL:SM-G981N
PRODUCT:x1qksx
TAGS:release-keys
VERSION.INCREMENTAL:G981NKSU3IWCG
VERSION.RELEASE:13
VERSION.SDK_INT:33
Locale:eu_ES
configuration:{0.8 ?mcc?mnc [eu_ES,es_ES] ldltr sw411dp w411dp h869dp 420dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 78 - 1080, 2361) mMaxBounds=Rect(0, 0 - 1080, 2400) mDisplayRotation=ROTATION_0 mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0 mPopOver=undefined mStageConfig=undefined mFreeformTaskPinningState=undefined mFreeformStashState=undefined mDexTaskDockingState=undefined} as.4 s.532 fontWeightAdjustment=0 ff=0 bf=0 bts=0 desktop/d dm/n ?dc ?dcui themeSeq=1 nightDim=0}
That's all I know.
******************************
****** Log-Cat: 
Log contains 0 lines:

**Comment by mirenbz** [comment]
I imporelted them from my old phone. They did work back there, with the F-Droid version if I'm not wrong. But i needed to upgrade to the beta in order for the import of settings to work.

If nothing else, I could go back to vanilla and re-set all my old settings by hand (would rather avoid that though), if I remember them...

**Comment by menny** [comment]
Is it possible to attach the backup file here? If so, make sure it does not include in private info. And if you redact or remove anything, let me what key

**Comment by menny** [comment]
Is it possible to attach the backup file here? If so, make sure it does not include in private info. And if you redact or remove anything, let me what key

**Comment by NicoHood** [comment]
Hi, I also have this issue and it happened randomly like every 2-3 Month. But not it happens ALWAYS and I dont know why.

For some random fact: I am using the Android Business Mode, where you can install apps twice. Inside the business profile and the normal one. I have anysoft keyboard installed on both and only the normal profile runs into issue (when using normal apps). But I have no other clue what the correlation is to reproduce the bug.

**Comment by NicoHood** [comment]
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 19:00:03 20.07.2025
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.12.1098 release 8726. Installed on 1752817588818, first release installed was 7137.
******************************
java.lang.IllegalArgumentException
****** Exception message: can not have skin-tone set to null!

**Comment by NicoHood** [comment]
Why does this not get fixed @menny ? This bug is open for years and not even the workarounds help me. This is really sad :-/
