### ISSUE TITLE
Problem copy-paste

### ISSUE THREAD

**Issue by niknik-ykt** [AnySoftKeyboard/AnySoftKeyboard#2030]
I have regular problems with the clipboard. the application freezes, closing part of the screen. sometimes the phone freezes

Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 02:01:07 10.02.2020
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.10.1096 release 6266. Installed on 1578875921010, first release installed was 3692.
******************************
****** Exception type: java.lang.NullPointerException
****** Exception message: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
****** Trace trace:
at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:401)
at android.widget.ArrayAdapter.getView(ArrayAdapter.java:369)
at android.widget.AbsListView.obtainView(AbsListView.java:2370)
at android.widget.ListView.makeAndAddView(ListView.java:1884)
at android.widget.ListView.fillDown(ListView.java:706)
at android.widget.ListView.fillGap(ListView.java:670)
at android.widget.AbsListView.trackMotionScroll(AbsListView.java:5255)
at android.widget.AbsListView$FlingRunnable.run(AbsListView.java:4798)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:886)
at android.view.Choreographer.doCallbacks(Choreographer.java:698)
at android.view.Choreographer.doFrame(Choreographer.java:630)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:872)
at android.os.Handler.handleCallback(Handler.java:743)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5659)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

******************************
****** Device information:
BRAND:HUAWEI
DEVICE:HWDIG-L8940
Build ID:Diego-L21HNC10B122
changelist number:HUAWEIDIG-L21HN
MODEL:DIG-L21HN
PRODUCT:DIG-L21HN
TAGS:release-keys
VERSION.INCREMENTAL:C10B122
VERSION.RELEASE:6.0
VERSION.SDK_INT:23
Locale:ru_RU
configuration:{1.0 250mcc2mnc ru_RU ldltr sw360dp w360dp h580dp 320dpi nrml port finger -keyb/v/h -nav/h suim:1 s.135}
That's all I know.******************************
****** Log-Cat:
Log contains 0 lines:

**Comment by menny** [comment]
can you try this with the latest beta version?

**Comment by menny** [comment]
closing as this does not happen anymore
