### ISSUE TITLE
Switch Keyboard function not activated when installed as system app on Samsung device(s).

### ISSUE THREAD

**Issue by vdbhb59** [AnySoftKeyboard/AnySoftKeyboard#2346]
In certain Samsung devices, especially on Android 10, which are rooted via magical boot patch, and where there is no custom recovery option, when one places ASK in /system/system/app, and reboots, the keyboard does not have the toggle activated under keyboard option. Even after giving proper permission it still does not work, nor installing over system app too.
### Steps to reproduce
1. Copy ASK folder with apk inside to /system/system/app. 
2. Grant 0755 to folder and 0644 to apk and reboot to system.
3. Navigate to keyboard switch option (via settings or via ask apk redirect).
4. Try to change keyboard: toggle for on-off for keyboard should be toggalable.

### Expected behaviour
Tell us what should happen

Keyboard should be allowed to toggle On-Off.

### Actual behaviour
Tell us what happens instead

In Samsung devices, the option is greyed out.

**Android OS version:**
10
**Device manufacturer and model:**
Samsung, M305F

**List of installed add-ons (like languages, or themes):**
None yet.
![Screenshot_20200621-201412_Settings](https://user-images.githubusercontent.com/60728004/85227856-6c9c3480-b3cf-11ea-9d92-ab4a90be8aad.png)

**Comment by menny** [comment]
This is interesting, I didn't try installing the keyboard as root for a while now,  but i recall you need to copy the native SO file somewhere...

**Comment by vdbhb59** [comment]
I tried finding the details through various modes, even ASK git, but did not find anything anywhere. Would you be able to check and guide, please?

**Comment by menny** [comment]
https://github.com/AnySoftKeyboard/AnySoftKeyboard/wiki/Installing-AnySoftKeyboard-on-System-Partition

**Comment by vdbhb59** [comment]
Thanks mate. Also, can you look up the other issue I opened for F-Droid updates?

**Comment by vdbhb59** [comment]
@menny So, I did that, but as usual, after giving storage permission,  and trying to restore, the pop-up does not come. As I mentioned earlier, only after installing as user app over system app does it work. No reboot, no using oat and so files help. I think it maybe due to certain default permission or background permission of some sort not provided for by default.

**Comment by menny** [comment]
Can you check the logcat for errors?

**Comment by vdbhb59** [comment]
No Logcat as it overrides on reboot, and I have to reboot for any app manually placed

**Comment by vdbhb59** [comment]
@menny - Hope this helps..

# **`pm grant com.menny.android.anysoftkeyboard android.permission.WRITE_SETTINGS`**
Security exception: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.WRITE_SETTINGS

java.lang.SecurityException: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.WRITE_SETTINGS
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:433)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2931)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2895)
        at com.android.server.pm.permission.PermissionManagerService.access$1200(PermissionManagerService.java:156)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3966)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6880)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26851)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5055)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)

Also

# **`pm grant com.menny.android.anysoftkeyboard android.permission.WRITE_SECURE_SETTINGS`**
Security exception: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.WRITE_SECURE_SETTINGS

java.lang.SecurityException: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.WRITE_SECURE_SETTINGS
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:433)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2931)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2895)
        at com.android.server.pm.permission.PermissionManagerService.access$1200(PermissionManagerService.java:156)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3966)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6880)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26851)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5055)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
grant com.menny.android.anysoftkeyboard android.permission.CHANGE_CONFIGURATION                                       <
Security exception: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.CHANGE_CONFIGURATION

java.lang.SecurityException: Package com.menny.android.anysoftkeyboard has not requested permission android.permission.CHANGE_CONFIGURATION
        at com.android.server.pm.permission.BasePermission.enforceDeclaredUsedAndRuntimeOrDevelopment(BasePermission.java:433)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2931)
        at com.android.server.pm.permission.PermissionManagerService.grantRuntimePermission(PermissionManagerService.java:2895)
        at com.android.server.pm.permission.PermissionManagerService.access$1200(PermissionManagerService.java:156)
        at com.android.server.pm.permission.PermissionManagerService$PermissionManagerServiceInternalImpl.grantRuntimePermission(PermissionManagerService.java:3966)
        at com.android.server.pm.PackageManagerService.grantRuntimePermission(PackageManagerService.java:6880)
        at com.android.server.pm.PackageManagerShellCommand.runGrantRevokePermission(PackageManagerShellCommand.java:1955)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:230)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26851)
        at android.os.Binder.shellCommand(Binder.java:881)
        at android.os.Binder.onTransact(Binder.java:765)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5055)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
