### ISSUE TITLE
Keyboard crashes when pressing "shift"

### ISSUE THREAD

**Issue by kate-shine** [AnySoftKeyboard/AnySoftKeyboard#2481]
Keyboard freezes and crashes when pressing shift key after sending a message in [Fluffychat](https://gitlab.com/ChristianPauly/fluffychat-flutter) matrix client (might be also related to flutter framework)

### Steps to reproduce
1. Send a message
2. Hit shift key to start the next message with a capital letter
3. Keyboard freezes and crashes

Logcat output: https://paste.rs/g1Q

### Expected behaviour
Even if the Flutter framework or Fluffychat do something causing the keyboard to crash, it should catch it and not crash :)

### Actual behaviour
Keyboard freezes and gets stuck on the screen, whole system becomes way less responsive.
After some time, the keyboard process crashes and starts again.

**Android OS version:**
Motorola: Android 10, September 1, 2020 security patch
Xperia: Lineage OS 17.1

**Device manufacturer and model:**
Motorola One Vision, Sony Xperia 10

**List of installed add-ons (like languages, or themes):**
Czech, English and German languages

**Comment by kate-shine** [comment]
Update: Crash is caused by Selection Offset being -1 when editable text is changed, which is a default Flutter behavior.

https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/editable_text.dart#L160

**Comment by menny** [comment]
This is a great find. We'll fix this.

**Comment by menny** [comment]
@kate-shine, Can you give me either a crash stacktrace or a flutter app I can test against?

**Comment by kate-shine** [comment]
@menny The app and way to reproduce is described in OP. It needs an account, but creating a disposable matrix account in it is easy and doesn't need any personal details.

I should have time to create more logs than the logcat paste in OP later this weekend, do you need anything specific?

**Comment by menny** [comment]
I need a logcat from the time of the crash

**Comment by menny** [comment]
Okay. Got it to crash. Thanks

**Comment by kate-shine** [comment]
The linked logcat is from the crash :) But maybe it's missing something? Anyway, doesn't matter now, probably. Thank you :)

**Comment by menny** [comment]
```
11-13 13:14:28.807  1632  5004 E NotificationService: No Channel found for pkg=com.menny.android.anysoftkeyboard, channelId=null, id=2131296443, tag=null, opPkg=com.menny.android.anysoftkeyboard, callingUid=10395, userId=0, incomingUserId=0, notificationUid=10395, notification=Notification(channel=null shortcut=null contentView=null vibrate=default sound=null tick defaults=0x6 flags=0x19 color=0xffff3333 vis=PRIVATE)
11-13 13:14:28.807  5169  5169 I ASKChewbacca: Sending the exception to OS exception handler...
11-13 13:14:28.807  5169  5169 W System.err: java.lang.StringIndexOutOfBoundsException: length=0; index=-1
11-13 13:14:28.807  5169  5169 W System.err: 	at java.lang.String.substring(String.java:2057)
11-13 13:14:28.807  5169  5169 W System.err: 	at java.lang.String.subSequence(String.java:2107)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.AnySoftKeyboard.toggleCaseOfSelectedCharacters(AnySoftKeyboard.java:1088)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.AnySoftKeyboard.onPress(AnySoftKeyboard.java:1162)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.PointerTracker.onDownEvent(PointerTracker.java:260)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.onDownEvent(AnyKeyboardViewBase.java:2084)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.sendOnXEvent(AnyKeyboardViewBase.java:2064)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.onTouchEvent(AnyKeyboardViewBase.java:2039)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewWithMiniKeyboard.onTouchEvent(AnyKeyboardViewWithMiniKeyboard.java:108)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onTouchEvent(AnyKeyboardView.java:352)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.View.dispatchTouchEvent(View.java:14309)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2742)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
11-13 13:14:28.807  5169  5169 W System.err: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1871)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
11-13 13:14:28.807  5169  5169 W System.err: 	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:160)
11-13 13:14:28.808  5169  5169 W System.err: 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.View.dispatchPointerEvent(View.java:14568)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6016)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5819)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5310)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5485)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5542)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5367)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5333)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5341)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5314)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8080)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8031)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7992)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8203)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.os.MessageQueue.nativePollOnce(Native Method)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.os.MessageQueue.next(MessageQueue.java:335)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.os.Looper.loop(Looper.java:183)
11-13 13:14:28.808  5169  5169 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7656)
11-13 13:14:28.808  5169  5169 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
11-13 13:14:28.808  5169  5169 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
11-13 13:14:28.808  5169  5169 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
11-13 13:14:28.808  5169  5169 E ASK_FATAL: Fatal Java error 'length=0; index=-1' on thread 'Thread[main,5,main]'
11-13 13:14:28.808  5169  5169 E ASK_FATAL: java.lang.StringIndexOutOfBoundsException: length=0; index=-1

```
