### ISSUE TITLE
Cannot install app or dictionaries via play store on work profile / GrapheneOS

### ISSUE THREAD

**Issue by ni-ka** [AnySoftKeyboard/AnySoftKeyboard#3560]
### Steps to reproduce
1. On a phone with a work profile set up via Shelter app on GrapheneOS
2. Install AnySoftKeyboard from play store
3.

### Expected behaviour
AnySoftKeyboard should install

### Actual behaviour
AnySoftKeyboard installation fails

![Screenshot_20221202-132408](https://user-images.githubusercontent.com/1225776/205303490-1c3558a0-1bce-4e85-8105-1cd8a5458d4f.png)

**Android OS version:**'
Version 13 GrapheneOS

**Device manufacturer and model:**
Google Pixel 6a

**List of installed add-ons (like languages, or themes):**

**Comment by menny** [comment]
This is interesting.. Can you provide a logcat with the failure?

**Comment by ni-ka** [comment]
Hey @menny,

Sorry for the delay - busy times! Here is the log. fyi i have anysoftkeyboard + some dictionaries installed in my main profile as well (from fdroid).

```
12-16 09:05:35.007  1472  6506 I ActivityTaskManager: START u10 {act=android.content.pm.action.CONFIRM_INSTALL pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.InstallStart (has extras)} from uid 1010152
12-16 09:05:35.008  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 194480991; UID 1010046; state: ENABLED
12-16 09:05:35.009  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 174042980; UID 1010046; state: DISABLED
12-16 09:05:35.010  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 184838306; UID 1010046; state: DISABLED
12-16 09:05:35.010  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 185004937; UID 1010046; state: DISABLED
12-16 09:05:35.010  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 181136395; UID 1010046; state: DISABLED
12-16 09:05:35.011  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 174042936; UID 1010046; state: DISABLED
12-16 09:05:35.020 11679 11679 I Finsky  : [2] mzr.apply(31): IQ::HLD: Ongoing hold off applicable installs: []
12-16 09:05:35.022  1472  6506 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (3973219)
12-16 09:05:35.023  1472  6506 D CompatibilityChangeReporter: Compat change id reported: 168419799; UID 1010046; state: DISABLED
12-16 09:05:35.026 11679 11679 I Finsky  : [2] mzr.apply(31): IQ::HLD: Ongoing hold off applicable installs: []
12-16 09:05:35.032  1472  2384 I ActivityTaskManager: START u10 {act=android.content.pm.action.CONFIRM_INSTALL flg=0x2000001 pkg=com.android.packageinstaller cmp=com.android.packageinstaller/.PackageInstallerActivity (has extras)} from uid 1010046
12-16 09:05:35.039  1472  4524 W ActivityTaskManager: Tried to set launchTime (0) < mLastActivityLaunchTime (3992508)
12-16 09:05:35.052 11679 12775 I Finsky  : [242] jsl.run(6): Installer: Session time: 0 seconds
12-16 09:05:35.061  1472  4524 D CoreBackPreview: Window{57e227f u10 com.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7b6a295, mPriority=0}
12-16 09:05:35.079  1472  1546 I ActivityTaskManager: Displayed com.android.packageinstaller/.PackageInstallerActivity: +68ms
12-16 09:05:35.233  1153  1153 D AOC     : A3:MSG: vsc_controller.cc, 491: VSC: [Significant Motion] requestSensorEvents: sensor 0x20002, period=18446744073709 la
12-16 09:05:35.233  1153  1153 D AOC     : A3:MSG: usf_sensor.cc, 1357: USF: Received start sampling request for LSM6DSR Motion Detect.
12-16 09:05:35.234  1153  1153 D AOC     : A3:MSG: vsc_controller.cc, 509: VSC: [Significant Motion] stopSensorEvents: sensor 0x10001
12-16 09:05:35.237  1153  1153 D AOC     : A3:MSG: usf_sensor.cc, 1872: USF: Received reconfig sampling request for LSM6DSR Accelerometer.
12-16 09:05:35.238  1153  1153 D AOC     : A3:MSG: lsm6dsr_device.cc, 755: USF: Lsm6dsrDevice: Sensor 0: Enabled 1, odr_index 3.
12-16 09:05:35.238  1153  1153 D AOC     : A3:MSG: lsm6dsr_fifo.cc, 754: USF: Lsm6dsrFifo: ODR: XL/G/T/TS: 52/52/13/6 WM: 4 Intr: 31.
12-16 09:05:35.239  1153  1153 D AOC     : A3:MSG: lsm6dsr_device.cc, 663: USF: Lsm6dsrDevice: Fifo was disabled for 543213ns.
12-16 09:05:35.925   971   971 I WifiHAL : Creating message to get link statistics; iface = 47
12-16 09:05:35.956  7600  7600 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.facs.internal.service.START dat=chimera-action:/... cmp=com.google.android.gms/.chimera.GmsInternalApiService }
12-16 09:05:36.012  3158  3158 D BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.facs.cache.service.START pkg=com.google.android.gms }
12-16 09:05:36.026   971   971 I WifiHAL : In GetLinkStatsCommand::handleResponse
12-16 09:05:36.919 12648 12719 I Finsky:background: [20] jzz.h(2): DownloadService is getting stopped.
12-16 09:05:36.922 11679 11679 W Finsky  : [2] ftf.g(3): No LoggingContext in the bundle, which breaks event chain!. Creating a new logging context.
12-16 09:05:36.922 12648 12648 I Finsky:background: [2] DownloadService.onDestroy(5): DownloadService is getting destroyed.
12-16 09:05:37.227  1684  1694 I native  : I0000 00:00:1671181537.226777    1694 tf_lite_classifier.cc:383] Event stream classified as kNone
12-16 09:05:37.251  1472  1617 E PackageManager: ERROR: could not load root hash from incremental install
12-16 09:05:37.251  1472  1617 E PackageManager: ERROR: could not load root hash from incremental install
12-16 09:05:37.251  1472  1617 E PackageManager: Required verifier is null
12-16 09:05:37.270  1472  1687 W AppIntegrityManagerServiceImpl: Installer package com.android.vending not found.
12-16 09:05:37.278  1472  1687 W RuleEvaluation: Integrity rule files are not available.
12-16 09:05:37.280  1472  1617 I PackageManager: Integrity check passed for file:///data/app/vmdl840704958.tmp
12-16 09:05:37.292  1472  1617 W PackageManager: Existing package com.anysoftkeyboard.languagepack.german signatures do not match newer version; ignoring!
12-16 09:05:37.293  1472  1617 D PackageInstallerSession: Marking session 840704958 as failed: INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.anysoftkeyboard.languagepack.german signatures do not match newer version; ignoring!
12-16 09:05:37.293  1077  1096 E installd: Couldn't opendir /data/app/vmdl840704958.tmp: No such file or directory
12-16 09:05:37.293  1077  1096 E installd: Failed to delete /data/app/vmdl840704958.tmp: No such file or directory
12-16 09:05:37.298 11679 11679 I Finsky  : [2] nfx.e(1): Submitter: commit of com.anysoftkeyboard.languagepack.german failed with 6004
12-16 09:05:37.298 11679 11679 E Finsky  : [2] nfx.e(2): Submitter: commit error message INSTALL_FAILED_UPDATE_INCOMPATIBLE: Existing package com.anysoftkeyboard.languagepack.german signatures do not match newer version; ignoring!
12-16 09:05:37.301 11679 12637 E Finsky  : [212] muy.a(5): IV2: Task Failed: tid:1000000084, statusCode:6004
12-16 09:05:37.301 11679 12637 E Finsky  : com.google.android.finsky.installerv2.InstallerException: Status: 6004
12-16 09:05:37.301 11679 12637 E Finsky  : 	at nfw.apply(PG:8)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at ajpn.e(PG:2)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at ajpo.run(PG:9)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at htu.run(PG:12)
12-16 09:05:37.301 11679 12637 E Finsky  : 	at java.lang.Thread.run(Thread.java:1012)
12-16 09:05:37.301 11679 12637 I Finsky  : [212] muy.a(9): IV2: Finishing up unsuccessful install: 84, installState: 5
12-16 09:05:37.303 11679 11771 I Finsky  : [32] mvj.a(21): IV2::TM: canceling tid: 1000000084
12-16 09:05:37.303 11679 11771 I Finsky  : [32] mvg.c(7): Submitter: already started, can't be canceled.
12-16 09:05:37.304 11679 11771 I Finsky  : [32] mvg.c(8): IV2::TD cancel not possible, submitter already started.
12-16 09:05:37.304 11679 11776 I Finsky  : [35] mvj.a(5): IV2::TM: cleaning up tid: 1000000084
12-16 09:05:37.304 11679 11776 I Finsky  : [35] mvj.a(9): IV2:TM: cleaning up task. com.anysoftkeyboard.languagepack.german[iid:84] [isid:mlGBHMKoQnSnXxGY6jrnhQ] [tid: 1000000084]
12-16 09:05:37.305  1472  6506 D CoreBackPreview: Window{57e227f u10 com.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity}: Setting back callback null
12-16 09:05:37.306 11679 11775 I Finsky  : [34] ugp.m(1): RM: remove resources for request f1185d2f-b673-42ff-813e-7fb3f4aab287
12-16 09:05:37.307 11679 11775 I Finsky  : [34] ugp.m(1): RM: remove resources for request 0ba49dfb-c0b9-4591-be33-c6ecf894447d
12-16 09:05:37.307 11679 11775 I Finsky  : [34] ugp.m(1): RM: remove resources for request de8a013c-6604-4595-9474-3889135cee31
12-16 09:05:37.307 12552 12588 D OpenGLRenderer: endAllActiveAnimators on 0xb400ccf0132a9100 (RippleDrawable) with handle 0xb400cbd12ff1a0f0
12-16 09:05:37.308  1472  4524 W InputManager-JNI: Input channel object '57e227f com.android.packageinstaller/com.android.packageinstaller.PackageInstallerActivity (client)' was disposed without first being removed with the input manager!
12-16 09:05:37.308 11679 11749 I Finsky  : [15] kap.h(1): remove(825)
12-16 09:05:37.308 11679 11752 I Finsky  : [17] kap.h(1): remove(824)
12-16 09:05:37.308 11679 11754 I Finsky  : [18] kap.h(1): remove(823)
12-16 09:05:37.309 12648 13103 I Finsky:background: [39] jxp.g(1): remove(request_id=823)
12-16 09:05:37.309 12648 13104 I Finsky:background: [40] jxp.g(1): remove(request_id=825)
12-16 09:05:37.309 12648 13102 I Finsky:background: [38] jxp.g(1): remove(request_id=824)
12-16 09:05:37.321 12648 12719 I Finsky:background: [20] jxp.d(21): onRemove(request_id=823, files_to_download=1, group_id=com.anysoftkeyboard.languagepack.german, display_data[invisible=false, title=German for AnySoftKeyboard], network_restrictions=4, status=succeeded, bytes_downloaded=8445, total_bytes=8445, retry[count=0, next_retry=n/a])
12-16 09:05:37.326 12648 12719 I Finsky:background: [20] jxp.d(21): onRemove(request_id=825, files_to_download=1, group_id=com.anysoftkeyboard.languagepack.german, display_data[invisible=false, title=German for AnySoftKeyboard], network_restrictions=4, status=succeeded, bytes_downloaded=6880, total_bytes=6880, retry[count=0, next_retry=n/a])
12-16 09:05:37.327 11679 12643 I Finsky  : [218] naq.P(2): IQ: Notifying installation update. [Package:com.anysoftkeyboard.languagepack.german, isid:mlGBHMKoQnSnXxGY6jrnhQ], status=INSTALL_ERROR
12-16 09:05:37.330 11679 12645 I Finsky  : [220] rsp.l(2): Session is stale, session is not alive: getNames not allowed after destruction
12-16 09:05:37.330 11679 12645 I Finsky  : [220] uef.a(119): SM: Session with Context {name=com.anysoftkeyboard.languagepack.german versionCode=3574} was closed or abandoned in a consumer.
12-16 09:05:37.332 11679 12637 I Finsky  : [212] mug.a(120): IV2: Successfully abandon the session for com.anysoftkeyboard.languagepack.german[iid:84] [isid:mlGBHMKoQnSnXxGY6jrnhQ]
12-16 09:05:37.334 11679 11679 I Finsky  : [2] moc.r(12): IT: DL session turned off due to Incremental install not requested: com.anysoftkeyboard.languagepack.german
12-16 09:05:37.335 11679 11679 I Finsky  : [2] tnb.aac(6): PIM: Handling install package event for: com.anysoftkeyboard.languagepack.german status:  INSTALL_ERROR, isid: mlGBHMKoQnSnXxGY6jrnhQ
12-16 09:05:37.335 11679 11679 I Finsky  : [2] tnb.aac(7): PIM: Stopping icon download for com.anysoftkeyboard.languagepack.german
12-16 09:05:37.335 11679 11679 I Finsky  : [2] tmy.b(1): Canceling bitmap for com.anysoftkeyboard.languagepack.german
12-16 09:05:37.336 12648 12719 I Finsky:background: [20] jxp.d(21): onRemove(request_id=824, files_to_download=1, group_id=com.anysoftkeyboard.languagepack.german, display_data[invisible=false, title=German for AnySoftKeyboard], network_restrictions=4, status=succeeded, bytes_downloaded=2081717, total_bytes=2081717, retry[count=0, next_retry=n/a])
12-16 09:05:37.336 11679 11760 I Finsky  : [24] gzd.b(3): AU2: Failure History successfully updated for package com.anysoftkeyboard.languagepack.german, attempting to upgrade to version 3574 with install reason SINGLE_INSTALL and status_code 6004
12-16 09:05:37.339 11679 11776 I Finsky  : [35] mus.a(70): IQ: start evaluating install requests.
12-16 09:05:37.341 11679 11776 I Finsky  : [35] mus.a(80): IQ: 0 pending for job: 338
12-16 09:05:37.341 11679 11776 I Finsky  : [35] mus.a(81): IQ: Finishing job 338
12-16 09:05:37.341 11679 11776 I Finsky  : [35] umy.r(4): SCH: jobFinished: 3-338. TimeElapsed: 3657ms.
12-16 09:05:37.341 11679 11776 I Finsky  : [35] mus.a(88): IQ: No matching installs to run for jobs: [338]
12-16 09:05:37.342 11679 11776 I Finsky  : [35] mus.a(91): IQ: no installs to evaluate. Skipping.

```

**Comment by SmitaAland** [comment]
How you resolved this issue? I am getting similar issue in Pixel 6a OS 14 device.

**Comment by ni-ka** [comment]
@SmitaAland unfortunately not it is still happening, are you also using grapheneos or just regular google OS and a work profile?

Cheers!

**Comment by SmitaAland** [comment]
@ni-ka Thanks for quick response. I am using regular android native app. If this issue is still not resolved for you, how are proceedings with the app now?
