### ISSUE TITLE
[Crash] NullPointerException : Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference

### ISSUE THREAD

**Issue by Massedil** [AnySoftKeyboard/AnySoftKeyboard#3561]
The keyboard stays displayed, but does not react. The Android interface is available behind the keyboard. I can open the other apps. I need to wait a long time (30 seconds ?) with the keyboard printed on every app screen I try, until the Android interface permit me to kill AnySoftKeyboard. 

### Steps to reproduce

I don't know. I'm using the keyboard and suddenly it blocks. 
The bug is rare, but it happens sometimes. Maybe 1 or 2 times per month ?

- Android OS version: LineageOS 18.1 / Android 11

- Device manufacturer and model: Samsung Galaxy S5 (klte)

- List of installed add-ons (like languages, or themes): French Language pack

### Logs

```
12-01 22:48:10.562 E/InputEventReceiver(6305): Exception dispatching input event.
12-01 22:48:10.562 E/MessageQueue-JNI(6305): Exception in MessageQueue callback: handleReceiveCallback
12-01 22:48:10.661 E/MessageQueue-JNI(6305): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.ime.AnySoftKeyboardWithGestureTyping.t(Unknown Source:15)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at c.b.z.r0.x0.a(Unknown Source:2)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at c.b.z.r0.x0.h(Unknown Source:8)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.y(Unknown Source:10)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.y(Unknown Source:0)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.z(Unknown Source:43)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.onTouchEvent(Unknown Source:25)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at c.b.z.r0.g0.onTouchEvent(Unknown Source:2)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onTouchEvent(Unknown Source:19)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.View.dispatchTouchEvent(View.java:14309)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1873)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:160)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.View.dispatchPointerEvent(View.java:14568)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6022)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8086)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8037)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7998)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8209)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.os.MessageQueue.next(MessageQueue.java:335)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.os.Looper.loop(Looper.java:183)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at java.lang.reflect.Method.invoke(Native Method)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-01 22:48:10.661 E/MessageQueue-JNI(6305): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

[...]

12-01 22:48:10.680 E/AndroidRuntime(6305): FATAL EXCEPTION: main
12-01 22:48:10.680 E/AndroidRuntime(6305): Process: com.menny.android.anysoftkeyboard, PID: 6305
12-01 22:48:10.680 E/AndroidRuntime(6305): java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.ime.AnySoftKeyboardWithGestureTyping.t(Unknown Source:15)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at c.b.z.r0.x0.a(Unknown Source:2)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at c.b.z.r0.x0.h(Unknown Source:8)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.y(Unknown Source:10)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.y(Unknown Source:0)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.z(Unknown Source:43)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardViewBase.onTouchEvent(Unknown Source:25)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at c.b.z.r0.g0.onTouchEvent(Unknown Source:2)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onTouchEvent(Unknown Source:19)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.View.dispatchTouchEvent(View.java:14309)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3118)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2799)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:488)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1873)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.app.Dialog.dispatchTouchEvent(Dialog.java:859)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:160)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:446)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.View.dispatchPointerEvent(View.java:14568)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:6022)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5825)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5316)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5491)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5548)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5373)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:5339)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:5347)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:5320)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:8086)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:8037)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7998)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:8209)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:220)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.os.MessageQueue.nativePollOnce(Native Method)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.os.MessageQueue.next(MessageQueue.java:335)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.os.Looper.loop(Looper.java:183)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at android.app.ActivityThread.main(ActivityThread.java:7664)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at java.lang.reflect.Method.invoke(Native Method)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
12-01 22:48:10.680 E/AndroidRuntime(6305): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
12-01 22:48:10.916 E/NotificationService(778): No Channel found for pkg=com.menny.android.anysoftkeyboard, channelId=Errors, id=2131296627, tag=null, opPkg=com.menny.android.anysoftkeyboard, callingUid=10335, userId=0, incomingUserId=0, notificationUid=10335, notification=Notification(channel=Errors shortcut=null contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x18 color=0xffff3333 vis=PRIVATE)
```

**Comment by menny** [comment]
a couple of questions:
1. Do you use gesture-typing a lot?
2. Which version of the keyboard are you using?
3. Does this happen in a specific app?

**Comment by Massedil** [comment]
1. No, nearly never, but gesture option is always activated. May be the problem occurs with a gesture start I don't want at this moment.

2. version 1.11.7137

3. Good question, I think not specific to an app, but I'm not sure. Last time was with Silence SMS app from F-Droid.
