### ISSUE TITLE
Crash when pressing the  "emoji" button in app settings

### ISSUE THREAD

**Issue by Aaroneisele55** [AnySoftKeyboard/AnySoftKeyboard#3574]
### Steps to reproduce
1. Use the beta version
2. Go into the AnySoftKeyboard app
3. Click the emoji button on the bottom of the screen

### Actual behaviour

**Android OS version:**
Version 12
**Device manufacturer and model:**
OnePlus Nord (AC2003)
**List of installed add-ons (like languages, or themes):**
German language package, German keyboard plugin (both from Play Store)

Crash Log:
`Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 07:33:09 17.12.2022
****** Application name: AnySoftKeyboard Canary (com.menny.android.anysoftkeyboard) v1.11.668 release 7628. Installed on 1671258687428, first release installed was 7137.
******************************
java.lang.IllegalArgumentException
****** Exception message: can not have both skin-tone and gender set to null!
----- FULL REPORT -----
****** Trace trace:
at l2.g.b(SourceFile:13)
at l2.o.i(SourceFile:200)
at l2.e.v(SourceFile:3)
at l2.e.i(SourceFile:35)
at l2.g.<init>(Unknown Source:20)
at com.anysoftkeyboard.quicktextkeys.ui.QuickTextKeysBrowseFragment.e0(SourceFile:63)
at b3.d.f(SourceFile:81)
at androidx.recyclerview.widget.i1.j(SourceFile:1255)
at androidx.recyclerview.widget.h0.b(SourceFile:59)
at androidx.recyclerview.widget.GridLayoutManager.Y0(SourceFile:116)
at androidx.recyclerview.widget.LinearLayoutManager.L0(SourceFile:54)
at androidx.recyclerview.widget.LinearLayoutManager.e0(SourceFile:878)
at androidx.recyclerview.widget.GridLayoutManager.e0(SourceFile:43)
at androidx.recyclerview.widget.RecyclerView.r(SourceFile:85)
at androidx.recyclerview.widget.RecyclerView.p(SourceFile:115)
at androidx.recyclerview.widget.RecyclerView.onLayout(Unknown Source:5)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at androidx.appcompat.widget.ActionBarOverlayLayout.onLayout(Unknown Source:49)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1841)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
at com.android.internal.policy.DecorView.onLayout(DecorView.java:873)
at android.view.View.layout(View.java:23330)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:3936)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3338)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2305)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9133)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1232)
at android.view.Choreographer.doCallbacks(Choreographer.java:1029)
at android.view.Choreographer.doFrame(Choreographer.java:934)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1217)
at android.os.Handler.handleCallback(Handler.java:938)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:233)
at android.os.Looper.loop(Looper.java:344)
at android.app.ActivityThread.main(ActivityThread.java:8212)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

******************************
****** Device information:
BRAND:OnePlus
DEVICE:Nord
Build ID:AC2003_11_F.16
changelist number:RKQ1.211119.001
MODEL:AC2003
PRODUCT:Nord_EEA
TAGS:release-keys
VERSION.INCREMENTAL:Q.202210141830
VERSION.RELEASE:12
VERSION.SDK_INT:31
Locale:de_DE
configuration:{1.1 ??mcc??mnc [de_DE] ldltr sw384dp w384dp h769dp 450dpi nrml long hdr widecg port night finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 1080, 2400) mAppBounds=Rect(0, 113 - 1080, 2276) mMaxBounds=Rect(0, 0 - 1080, 2400) mWindowingMode=fullscreen mDisplayWindowingMode=fullscreen mActivityType=undefined mAlwaysOnTop=undefined mRotation=ROTATION_0} as.2 s.830 fontWeightAdjustment=0mThemeChanged= 0, mThemeChangedFlags= 0, mFlipFont= 0, mAccessibleChanged= -1, mUxIconConfig= 3468918229192159505, mMaterialColor= 20000, mUserId= 0, mFontUserId= 0, mFontVariationSettings= 226, mFoldingAngle = -1.0, mIconPackName= , mDarkModeBackgroundMaxL= 0.0, mDarkModeDialogBgMaxL= 27.0, mDarkModeForegroundMinL= 100.0, mOplusConfigType= 1, mOplusChangedConfigs= 0, OpSans= 0}
That's all I know.
******************************
****** Log-Cat: 
Log contains 0 lines:`

**Comment by domportera** [comment]
seems like a duplicate of [this issue](https://github.com/AnySoftKeyboard/AnySoftKeyboard/issues/1860)

**Comment by Aaroneisele55** [comment]
Not using this anymore
