### ISSUE TITLE
IllegalArgumentException @ AndroidUserDictionary.AddWordToStorage(Unknown Source)

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#490]
Exception message: Unknown URL content://user_dictionary/words

at android.content.ContentResolver.delete(ContentResolver.java:1091)
at com.anysoftkeyboard.dictionaries.content.AndroidUserDictionary.AddWordToStorage(Unknown Source)
                                                                  deleteWordFromStorage
at com.anysoftkeyboard.dictionaries.BTreeDictionary.toLowerCase(Unknown Source)
                                                    addWord
                                                    deleteWord
                                                    deleteWordRec
                                                    registerObserver
                                                    getWords
                                                    isValidWord
                                                    getWordsRec
                                                    addWordRec
at com.anysoftkeyboard.dictionaries.BTreeDictionary.toLowerCase(Unknown Source)
                                                    addWord
                                                    deleteWord
                                                    deleteWordRec
                                                    registerObserver
                                                    getWords
                                                    isValidWord
                                                    getWordsRec
                                                    addWordRec
at com.anysoftkeyboard.dictionaries.UserDictionary.getWords(Unknown Source)
                                                   isValidWord
                                                   addWord
                                                   deleteWord
at com.anysoftkeyboard.keyboards.views.CandidateView.onTouchEvent(Unknown Source)
android.view.View.dispatchTouchEvent(View.java:7347)

**Comment by menny** [comment]
Not enough information.
