### ISSUE TITLE
IndexOutOfBoundsException @ AnyKeyboardBaseView.isAtTwoFingersState(Unknown Source)

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#492]
at java.util.LinkedList.get(LinkedList.java:519)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.isAtTwoFingersState(Unknown Source)
                                                           createKeyDetector
                                                           setValueFromTheme
                                                           setKeyIconValueFromTheme
                                                           getKeyboardStyleResId
                                                           reloadSwipeThresholdsSettings
                                                           setKeyboard
                                                           setShifted
                                                           guessLabelForKey
                                                           getIconToDrawForKey
                                                           hidePreview
                                                           invalidateKey
                                                           onLongPress
                                                           setPopupKeyboardWithView
                                                           generateMiniKeyboardMotionEvent
                                                           sendOnXEvent
                                                           onUpEvent
                                                           access$000
                                                           access$100
                                                           access$200
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.isAtTwoFingersState(Unknown Source)
                                                           createKeyDetector
                                                           setValueFromTheme
                                                           setKeyIconValueFromTheme
                                                           getKeyboardStyleResId
                                                           reloadSwipeThresholdsSettings
                                                           setKeyboard
                                                           setShifted
                                                           guessLabelForKey
                                                           getIconToDrawForKey
                                                           hidePreview
                                                           invalidateKey
                                                           onLongPress
                                                           setPopupKeyboardWithView
                                                           generateMiniKeyboardMotionEvent
                                                           sendOnXEvent
                                                           onUpEvent
                                                           access$000
                                                           access$100
                                                           access$200
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(Unknown Source)
at android.view.View.dispatchTouchEvent(View.java:8107)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)
android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2420)
android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2153)

**Comment by menny** [comment]
Not enough information
