### ISSUE TITLE
NPE @ View.getHardwareLayer

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#501]
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 14:51:42 06.09.2015
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.5.67-all release 257. Installed on 1441529079529, first release installed was 257.
******************************
****** Exception type: java.lang.NullPointerException
****** Exception message: null
****** Trace trace:
at android.view.View.getHardwareLayer(View.java:10320)
at android.view.ViewGroup.drawChild(ViewGroup.java:2877)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.getDisplayList(View.java:10557)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.support.v4.widget.DrawerLayout.drawChild(Unknown Source)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.draw(View.java:11123)
at android.view.View.getDisplayList(View.java:10559)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.draw(View.java:11123)
at android.widget.FrameLayout.draw(FrameLayout.java:450)
at android.view.View.getDisplayList(View.java:10559)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.draw(View.java:11123)
at android.support.v7.internal.widget.ActionBarOverlayLayout.draw(Unknown Source)
at android.view.View.getDisplayList(View.java:10559)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.getDisplayList(View.java:10557)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.getDisplayList(View.java:10557)
at android.view.ViewGroup.drawChild(ViewGroup.java:2864)
at android.view.ViewGroup.dispatchDraw(ViewGroup.java:2503)
at android.view.View.draw(View.java:11123)
at android.widget.FrameLayout.draw(FrameLayout.java:450)
at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2276)
at android.view.View.getDisplayList(View.java:10559)
at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:876)
at android.view.ViewRootImpl.draw(ViewRootImpl.java:2092)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1816)
at android.view.ViewRootImpl.handleMessage(ViewRootImpl.java:2628)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4517)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:993)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:760)
at dalvik.system.NativeStart.main(Native Method)

**Comment by menny** [comment]
I think this is related to Support Library 23.0.0 issue.
According to 23.0.1 change-log, there is an issue with hardware layer related code.

**Comment by menny** [comment]
http://developer.android.com/tools/support-library/index.html

**Comment by menny** [comment]
Fix in: https://github.com/AnySoftKeyboard/AnySoftKeyboard/commit/c5dbee5c6264c3fc9737b1d92abb095e9a7cf96b
