### ISSUE TITLE
ActivityNotFoundException for Intent { act=android.intent.action.VIEW dat=https://plus.google.com/u/0/communities/106050362696748221135 

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#516]
****** UTC Time: 21:59:49 22.10.2015
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.5.68-all release 258. Installed on 1444030987214, first release installed was 258.
******************************
****** Exception type: android.content.ActivityNotFoundException
****** Exception message: No Activity found to handle Intent { act=android.intent.action.VIEW dat=https://plus.google.com/u/0/communities/106050362696748221135 }
****** Trace trace:
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1409)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1379)
at android.app.Activity.startActivityForResult(Activity.java:2827)
at android.support.v4.app.n.a(Unknown Source)
at android.support.v4.app.p.a(Unknown Source)
at android.support.v4.app.Fragment.a(Unknown Source)
at com.anysoftkeyboard.ui.settings.q.onClick(Unknown Source)
at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:216)
at android.widget.TextView.onTouchEvent(TextView.java:6924)
at android.view.View.dispatchTouchEvent(View.java:3887)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:954)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1703)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1134)
at android.app.Activity.dispatchTouchEvent(Activity.java:2096)
at android.support.v7.internal.view.k.dispatchTouchEvent(Unknown Source)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1687)
at android.view.ViewRoot.deliverPointerEvent(ViewRoot.java:2194)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1878)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:144)
at android.app.ActivityThread.main(ActivityThread.java:3720)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:507)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
at dalvik.system.NativeStart.main(Native Method)

******************************
****** Device information:
BRAND:Lenovo
DEVICE:A396
Build ID:MDroid2.3.5
changelist number:MDroid2.3.5
MODEL:Lenovo A396
PRODUCT:A396
TAGS:test-keys
VERSION.INCREMENTAL:A396_S915_180529
VERSION.RELEASE:2.3.5
VERSION.SDK_INT:10
Locale:en_US
configuration:{ scale=1.0 imsi=502/12 loc=en_US touch=3 keys=1/1/2 nav=1/1 orien=1 layout=34 uiMode=17 seq=5}
That's all I know.******************************

**Comment by menny** [comment]
Decrypted stack-trace:
```
at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1409)
at android.app.Instrumentation.execStartActivity(Instrumentation.java:1379)
at android.app.Activity.startActivityForResult(Activity.java:2827)
at android.support.v4.app.FragmentActivity.dispatchFragmentsOnCreateView(Unknown Source)
                                           viewToString
                                           dumpViewHierarchy
                                           doReallyStop
                                           startActivityFromFragment$68747257
at android.support.v4.app.FragmentActivity$HostCallbacks.onDump$ec96877(Unknown Source)
                                                         onStartActivityFromFragment$68747257$46f3f89a
                                                         onFindViewById
                                                         onHasView
at android.support.v4.app.Fragment.instantiate(Unknown Source)
                                   instantiate
                                   setIndex
                                   setArguments
                                   getActivity
                                   getString
                                   getString
                                   setMenuVisibility
                                   startActivity
                                   onActivityResult
                                   onCreateAnimation
                                   onCreateView
                                   onViewCreated
                                   onCreateOptionsMenu
                                   onOptionsItemSelected
at com.anysoftkeyboard.ui.settings.MainFragment$2.onClick(Unknown Source)
at android.text.method.LinkMovementMethod.onTouchEvent(LinkMovementMethod.java:216)
at android.widget.TextView.onTouchEvent(TextView.java:6924)
at android.view.View.dispatchTouchEvent(View.java:3887)
```
