### ISSUE TITLE
UnsatisfiedLinkError @ NextWordDictionary.openNative

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#537]
****** UTC Time: 14:38:55 21.11.2015
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.6.133-all release 361. Installed on 1448084327999, first release installed was 361.

…

******************************
****** Exception type: java.lang.RuntimeException
****** Exception message: An error occured while executing doInBackground()
****** Trace trace:
at android.os.AsyncTask$3.done(AsyncTask.java:278)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)
*** Cause: java.lang.UnsatisfiedLinkError
** Message: openNative
** Stack track: at com.anysoftkeyboard.nextword.NextWordDictionary.openNative(Native Method)
at com.anysoftkeyboard.nextword.NextWordDictionary.<init>(Unknown Source)
at com.anysoftkeyboard.dictionaries.n.d(Unknown Source)
at com.anysoftkeyboard.b.a.a.c(Unknown Source)
at com.anysoftkeyboard.dictionaries.e.a(Unknown Source)
at com.anysoftkeyboard.dictionaries.e.doInBackground(Unknown Source)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:856)

******************************
****** Device information:
BRAND:Philips
DEVICE:Philips_WG-ROVER-RU_A
Build ID:Philips_W832_1250_V06_RU
changelist number:IMM76D
MODEL:Philips W832
PRODUCT:Philips_W832
TAGS:release-keys
VERSION.INCREMENTAL:eng.builder.1355225601
VERSION.RELEASE:4.0.4
VERSION.SDK_INT:15
Locale:ru_RU
configuration:{1.0 250mcc1mnc ru_RU layoutdir=0 sw360dp w360dp h614dp nrml long port finger -keyb/v/h -nav/h skin=/system/framework/framework-res.apk s.5}
That's all I know.******************************

**Comment by menny** [comment]
Disabling Next-Word JNI for now (it's not doing anything anyhow).
