### ISSUE TITLE
NPE @ MainFragment

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#546]
at com.anysoftkeyboard.ui.settings.MainFragment$4.onPostExecute(Unknown Source)
at android.os.AsyncTask.finish(AsyncTask.java:602)
at android.os.AsyncTask.access$600(AsyncTask.java:156)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:4507)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:980)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:747)
at dalvik.system.NativeStart.main(Native Method)

**Comment by menny** [comment]
Maybe `getView()` returns null in some cases?
