### ISSUE TITLE
NPE @ KeyboardSupport.createBackwardCompatibleStyleable

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#547]
t com.anysoftkeyboard.keyboards.KeyboardSupport.createBackwardCompatibleStyleable
at com.anysoftkeyboard.keyboards.Keyboard.<init>(Unknown Source)
at com.anysoftkeyboard.keyboards.AnyKeyboard.<init>(Unknown Source)
at com.anysoftkeyboard.keyboards.ExternalAnyKeyboard.<init>(Unknown Source)
at com.anysoftkeyboard.keyboards.KeyboardSwitcher.getEnabledKeyboardsBuilders(Unknown Source)
                                                  nextSymbolsKeyboard
                                                  getAlphabetKeyboard
at com.anysoftkeyboard.keyboards.KeyboardSwitcher.setInputView(Unknown Source)
                                                  getSymbolsKeyboard
                                                  getAlphabetKeyboards
                                                  makeKeyboards
                                                  setKeyboardMode
                                                  getKeyboardMode
                                                  nextAlphabetKeyboard
                                                  setKeyboard$6cd3d051
                                                  nextKeyboard
                                                  access$000
at com.anysoftkeyboard.keyboards.KeyboardSwitcher.setInputView(Unknown Source)
                                                  getSymbolsKeyboard
                                                  getAlphabetKeyboards
                                                  makeKeyboards
                                                  setKeyboardMode
                                                  getKeyboardMode
                                                  nextAlphabetKeyboard
                                                  setKeyboard$6cd3d051
                                                  nextKeyboard
                                                  access$000
at com.anysoftkeyboard.AnySoftKeyboard.getCursorPosition(Unknown Source)
                                       setSuggestions
                                       addToDictionaries
                                       removeFromUserDictionary
                                       onMultiTapStarted
                                       onKey
                                       showAllClipboardEntries
                                       setKeyboardStuffBeforeSetToView
                                       showOptionsDialogWithData
                                       onText
                                       abortCorrection$25decb5
                                       postUpdateSuggestions
                                       pickSuggestion
                                       isWordSeparator
                                       nextKeyboard
                                       setKeyboardFinalStuff
                                       onSwipeRight
                                       setInitialCondensedState
                                       showToastMessage$609c24db
                                       access$002
                                       access$100
                                       access$400
                                       access$600$5bf0a0bf
at com.anysoftkeyboard.AnySoftKeyboard.getCursorPosition(Unknown Source)
                                       setSuggestions
                                       addToDictionaries
                                       removeFromUserDictionary
                                       onMultiTapStarted
                                       onKey
                                       showAllClipboardEntries
                                       setKeyboardStuffBeforeSetToView
                                       showOptionsDialogWithData
                                       onText
                                       abortCorrection$25decb5
                                       postUpdateSuggestions
                                       pickSuggestion
                                       isWordSeparator
                                       nextKeyboard
                                       setKeyboardFinalStuff
                                       onSwipeRight
                                       setInitialCondensedState
                                       showToastMessage$609c24db
                                       access$002
                                       access$100
                                       access$400
                                       access$600$5bf0a0bf
at com.anysoftkeyboard.keyboards.views.PointerTracker.setKeyboard(Unknown Source)
                                                      getKey
                                                      isModifier
                                                      onDownEvent
                                                      onMoveEvent
                                                      isMinorMoveBounce
                                                      detectAndSendKey
                                                      getMultiTapCode
at com.anysoftkeyboard.keyboards.views.PointerTracker.isModifierInternal(Unknown Source)
                                                      onUpEvent
                                                      onCancelEvent
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.isAtTwoFingersState(Unknown Source)
                                                           createKeyDetector
                                                           setValueFromTheme
                                                           setKeyIconValueFromTheme
                                                           getKeyboardStyleResId
                                                           reloadSwipeThresholdsSettings
                                                           setKeyboard
                                                           setShifted
                                                           guessLabelForKey
                                                           getIconToDrawForKey
                                                           hidePreview
                                                           invalidateKey
                                                           invokeOnKey$6f2d30b1
                                                           onLongPress
                                                           setPopupKeyboardWithView
                                                           generateMiniKeyboardMotionEvent
                                                           sendOnXEvent
                                                           onUpEvent
                                                           access$000
                                                           access$100
                                                           access$200
at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.createKeyDetector(Unknown Source)
                                                       setKeyboard
                                                       setValueFromTheme
                                                       getKeyboardStyleResId
                                                       onLongPress
                                                       onUpEvent
                                                       requestInAnimation
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.isAtTwoFingersState(Unknown Source)
                                                           createKeyDetector
                                                           setValueFromTheme
                                                           setKeyIconValueFromTheme
                                                           getKeyboardStyleResId
                                                           reloadSwipeThresholdsSettings
                                                           setKeyboard
                                                           setShifted
                                                           guessLabelForKey
                                                           getIconToDrawForKey
                                                           hidePreview
                                                           invalidateKey
                                                           invokeOnKey$6f2d30b1
                                                           onLongPress
                                                           setPopupKeyboardWithView
                                                           generateMiniKeyboardMotionEvent
                                                           sendOnXEvent
                                                           onUpEvent
                                                           access$000
                                                           access$100
                                                           access$200
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(Unknown Source)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardView.onTouchEvent(Unknown Source)
at android.view.View.dispatchTouchEvent(View.java:7790)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2145)
at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1577)
at android.app.Dialog.dispatchTouchEvent(Dialog.java:757)
at android.inputmethodservice.SoftInputWindow.dispatchTouchEvent(SoftInputWindow.java:75)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2093)
at android.view.View.dispatchPointerEvent(View.java:7981)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4384)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4255)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3927)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3984)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6116)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6096)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6050)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6246)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5345)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)

**Comment by menny** [comment]
Closing till next release
