### ISSUE TITLE
ConcurrentModificationException @ AnyKeyboardBaseView

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#557]
****** UTC Time: 22:49:43 22.01.2016
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.6.167-all release 395. Installed on 1453438224005, first release installed was 362.
******************************
****** Exception type: java.util.ConcurrentModificationException
****** Exception message: null
****** Trace trace:
at java.util.LinkedList$LinkIterator.remove(LinkedList.java:167)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.a(Unknown Source)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.a(Unknown Source)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(Unknown Source)
at android.view.View.dispatchTouchEvent(View.java:7782)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.View.dispatchPointerEvent(View.java:7973)
at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4384)
at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4255)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3927)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3984)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3851)
at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3820)
at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3828)
at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3801)
at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6116)
at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6096)
at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6050)
at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6246)
at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
at android.os.MessageQueue.nativePollOnce(Native Method)
at android.os.MessageQueue.next(MessageQueue.java:138)
at android.os.Looper.loop(Looper.java:150)
at android.app.ActivityThread.main(ActivityThread.java:5323)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)

******************************
****** Device information:
BRAND:Ark_Electronic_Technology
DEVICE:ratech82_cwet_rlk_kk
Build ID:ARK__Benefit__I2__V009
changelist number:KOT49H
MODEL:ARK-Benefit I2
PRODUCT:ARK Benefit I2
TAGS:release-keys
VERSION.INCREMENTAL:eng.miracletek.1436845108
VERSION.RELEASE:4.4.2
VERSION.SDK_INT:19
Locale:ru_RU
configuration:{1.0 250mcc2mnc ru_RU ldltr sw360dp w360dp h567dp 320dpi nrml port finger -keyb/v/h -nav/h skin=/system/framework/framework-res.apk s.671}

**Comment by menny** [comment]
re-traced:
```
at java.util.LinkedList$LinkIterator.remove(LinkedList.java:167)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.releaseAllPointersOlderThan
onUpEvent
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.sendOnXEvent
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(Unknown Source)
at android.view.View.dispatchTouchEvent(View.java:7782)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2322)
at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2027)
at android.view.View.dispatchPointerEvent(View.java:7973)
```
