### ISSUE TITLE
ConcurrentModificationException @ AnyKeyboardBaseView.java:2151

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#597]
****** Exception type: java.util.ConcurrentModificationException
****** Exception message: null
****** Trace trace:
at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.a(AnyKeyboardBaseView.java:36336)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.a(AnyKeyboardBaseView.java:2151)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(AnyKeyboardBaseView.java:2132)
at android.view.View.dispatchTouchEvent(View.java:9297)

**Comment by menny** [comment]
```
at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView$PointerQueue.releaseAllPointersOlderThan(AnyKeyboardBaseView.java:36336)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.sendOnXEvent(AnyKeyboardBaseView.java:2151)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onTouchEvent(AnyKeyboardBaseView.java:2132)
at android.view.View.dispatchTouchEvent(View.java:9297)
```
