### ISSUE TITLE
NoSuchMethodError "android.view.KeyEvent.hasModifiers"

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#598]
****** Exception type: java.lang.NoSuchMethodError
****** Exception message: android.view.KeyEvent.hasModifiers
****** Trace trace:
at android.support.v7.app.ac.dispatchKeyEvent(AppCompatActivity.java:501)
at android.support.v7.view.n.dispatchKeyEvent(WindowCallbackWrapper.java:50)
at android.support.v7.app.ah.dispatchKeyEvent(AppCompatDelegateImplBase.java:241)
at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchKeyEvent(PhoneWindow.java:1643)
at android.view.ViewRoot.deliverKeyEventToViewHierarchy(ViewRoot.java:2471)
at android.view.ViewRoot.handleFinishedEvent(ViewRoot.java:2441)
at android.view.ViewRoot.handleMessage(ViewRoot.java:1735)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:123)
at android.app.ActivityThread.main(ActivityThread.java:4627)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:521)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
at dalvik.system.NativeStart.main(Native Method)

******************************
****** Device information:
BRAND:Huawei
DEVICE:msm7225
Build ID:U8150V100R001C367B856
changelist number:FRG83G
MODEL:Ideos
PRODUCT:Ideos
TAGS:release-keys
VERSION.INCREMENTAL:U8150C367B856
VERSION.RELEASE:2.2.2
VERSION.SDK_INT:8

**Comment by menny** [comment]
closing, so I'll get new crashes from the new release
