### ISSUE TITLE
NPE @ UiTweaksFragment

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#613]
Hi. It seems that we have crashed.... Here are some details:
****** UTC Time: 21:43:03 03.04.2016
****** Application name: AnySoftKeyboard (com.menny.android.anysoftkeyboard) v1.7.842 release 1237. Installed on 1459712232621, first release installed was 1237.
******************************
****** Exception type: java.lang.NullPointerException
****** Exception message: Attempt to invoke virtual method 'void android.preference.Preference.setOnPreferenceClickListener(android.preference.Preference$OnPreferenceClickListener)' on a null object reference
****** Trace trace:
at com.anysoftkeyboard.ui.settings.ad.a(UiTweaksFragment.java:46)
at android.support.v4.app.aa.a(FragmentManager.java:1086)
at android.support.v4.app.aa.a(FragmentManager.java:1252)
at android.support.v4.app.i.run(BackStackRecord.java:738)
at android.support.v4.app.aa.e(FragmentManager.java:1617)
at android.support.v4.app.ab.run(FragmentManager.java:517)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5624)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)

******************************
****** Device information:
BRAND:DOOGEE
DEVICE:hct6735m_35gu_l
Build ID:DOOGEE-X5pro-Android5.1-R12-2016.01.15
changelist number:LMY47D
MODEL:X5pro
PRODUCT:X5pro
TAGS:release-keys
VERSION.INCREMENTAL:1453092100
VERSION.RELEASE:5.1
VERSION.SDK_INT:22
Locale:hu_HU
configuration:{1.0 216mcc1mnc hu_HU ldltr sw360dp w360dp h615dp 320dpi nrml long port finger -keyb/v/h -nav/h s.6}
That's all I know.******************************
****** Log-Cat:
Not supported in RELEASE mode!

**Comment by menny** [comment]
```
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.closing(AnyKeyboardBaseView.java:2206)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onSharedPreferenceChanged(AnyKeyboardBaseView.java:2256)
at com.anysoftkeyboard.AskPrefsImpl.onSharedPreferenceChanged(AskPrefsImpl.java:541)
at com.menny.android.anysoftkeyboard.AnyApplication.onSharedPreferenceChanged(AnyApplication.java:94)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:476)
at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:384)
at android.preference.Preference.tryCommit(Preference.java:1437)
at android.preference.Preference.persistString(Preference.java:1470)
at android.preference.ListPreference.setValue(ListPreference.java:147)
at net.evendanan.pushingpixels.ListPreference.setValue(ListPreference.java:57)
at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
at android.preference.DialogPreference.onDismiss(DialogPreference.java:391)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5763)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
```

**Comment by menny** [comment]
Going to close for now.
