### ISSUE TITLE
NPE @ AnyKeyboardBaseView.closing

### ISSUE THREAD

**Issue by menny** [AnySoftKeyboard/AnySoftKeyboard#616]
```
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.closing(AnyKeyboardBaseView.java:2206)
at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onSharedPreferenceChanged(AnyKeyboardBaseView.java:2256)
at com.anysoftkeyboard.AskPrefsImpl.onSharedPreferenceChanged(AskPrefsImpl.java:541)
at com.menny.android.anysoftkeyboard.AnyApplication.onSharedPreferenceChanged(AnyApplication.java:94)
at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:476)
at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:384)
at android.preference.Preference.tryCommit(Preference.java:1437)
at android.preference.Preference.persistString(Preference.java:1470)
at android.preference.ListPreference.setValue(ListPreference.java:147)
at net.evendanan.pushingpixels.ListPreference.setValue(ListPreference.java:57)
at android.preference.ListPreference.onDialogClosed(ListPreference.java:282)
at android.preference.DialogPreference.onDismiss(DialogPreference.java:391)
at android.app.Dialog$ListenersHandler.handleMessage(Dialog.java:1278)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:194)
at android.app.ActivityThread.main(ActivityThread.java:5763)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
```

**Comment by menny** [comment]
```
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: java.lang.reflect.InvocationTargetException
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.preference.PreferenceManagerCompat.inflateFromResource(PreferenceManagerCompat.java:148)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.preference.PreferenceFragment.addPreferencesFromResource(PreferenceFragment.java:235)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.ui.settings.UiTweaksFragment.onCreate(UiTweaksFragment.java:40)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.Fragment.performCreate(Fragment.java:1951)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1029)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.BackStackRecord.ensureFragmentsAreInitialized(BackStackRecord.java:1077)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.BackStackRecord.beginTransition(BackStackRecord.java:1032)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:658)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1617)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:517)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.os.Handler.handleCallback(Handler.java:739)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.os.Looper.loop(Looper.java:148)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.app.ActivityThread.main(ActivityThread.java:5849)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at java.lang.reflect.Method.invoke(Native Method)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:763)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:653)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: Caused by: java.lang.RuntimeException: mPreviewPopupManager was already null!
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.closing(AnyKeyboardBaseView.java:2213)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onSharedPreferenceChanged(AnyKeyboardBaseView.java:2267)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.AskPrefsImpl.onSharedPreferenceChanged(AskPrefsImpl.java:541)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.menny.android.anysoftkeyboard.AnyApplication.onSharedPreferenceChanged(AnyApplication.java:95)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:479)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:387)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.preference.PreferenceManager.setNoCommit(PreferenceManager.java:605)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at android.preference.PreferenceManager.inflateFromResource(PreferenceManager.java:284)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	... 18 more
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: Caused by: java.lang.Exception
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.keyboards.views.AnyKeyboardBaseView.onViewNotRequired(AnyKeyboardBaseView.java:2248)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.AnySoftKeyboard.onCreateInputView(AnySoftKeyboard.java:377)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.AnySoftKeyboard.resetKeyboardView(AnySoftKeyboard.java:3035)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	at com.anysoftkeyboard.AnySoftKeyboard.onSharedPreferenceChanged(AnySoftKeyboard.java:2956)
04-07 14:58:33.273 27923 27923 W PreferenceManagerCompat: 	... 24 more
```
